fix: Don't alter the AST node positions of original code.
projectlombok/lombok pull request #3800
Opened 2024-12-21 07:54 UTC by amishra-u

2024-12-27 23:21 UTC, amishra-u commented
@Rawi01 Can you please review it.

2024-12-29 07:50 UTC, amishra-u commented
@Rawi01 In last run, the one check failed due to [timeout](https://github.com/projectlombok/lombok/actions/runs/12528525775/job/34947522581?pr=3800#step:4:4152). can you please rerun the check.

2025-01-03 12:09 UTC, Rawi01 requested changes
Thanks for your contribution, great work!

- Please add yourself to the `AUTHORS` file
- [`visitAnnotation` in `ValidateNoDuplicateTreeNodeProcessor`](https://github.com/projectlombok/lombok/pull/3800/files#diff-964e764e048f08907bd88b2e078f71ceea34399d030825fdd89d83f13bc4fe7cR347-R353) is no longer necessary and can be removed

2025-01-03 21:22 UTC, amishra-u commented on test/core/src/lombok/RunTestsViaDelombok.java
> +						if (lombokGeneratedNodes.isEmpty()) {
it is due to [this](https://github.com/projectlombok/lombok/blob/master/src/core/lombok/javac/handlers/HandleNonNull.java#L117) code, when a NonNull annotation is applied to a Record field, the NonNull handler modifies the compiler-generated constructor.  (I’ve also included these details in the PR summary).

2025-01-04 12:04 UTC, Rawi01 approved these changes

2025-01-04 12:04 UTC, Rawi01 commented on test/core/src/lombok/RunTestsViaDelombok.java
> +						if (lombokGeneratedNodes.isEmpty()) {
I noticed this in your PR summary but decided to test it anyway. At least the logger issue is something that should be fixed at some point. I already created a seperate issue (#3805) to not increase the scope of this PR. If you are interested in fixing it just let us know.

2025-01-04 12:11 UTC, merged

2025-01-07 13:38 UTC, timtebeek commented
hi @Rawi01 ; Thanks for the help getting this across the line! We're looking to leverage this downstream and I'm wondering what the release process looks like to get a local build. [The instructions are 14 years old](https://github.com/projectlombok/lombok/blob/master/doc/publishing.txt), so perhaps something has changed since?

I know it's always a pain when folks ask when the next release will be, but any indication would also be appreciated. 🙏🏻 
Looking forward to the changes made since the last release https://github.com/projectlombok/lombok/compare/v1.18.36...master